import { AUTH_PERMISSIONS } from "@/modules/auth/constants/auth.permissions";

export const MATERIAL_GRADES_PERMISSIONS = {
  READ: AUTH_PERMISSIONS.MATERIAL_GRADES_READ,
  CREATE: AUTH_PERMISSIONS.MATERIAL_GRADES_CREATE,
  UPDATE: AUTH_PERMISSIONS.MATERIAL_GRADES_UPDATE,
  DELETE: AUTH_PERMISSIONS.MATERIAL_GRADES_DELETE,
} as const;

export type MaterialGradesPermission =
  (typeof MATERIAL_GRADES_PERMISSIONS)[keyof typeof MATERIAL_GRADES_PERMISSIONS];
