import { AUTH_PERMISSIONS } from "@/modules/auth/constants/auth-permissions";

export const PASSES_PERMISSIONS = {
  READ: AUTH_PERMISSIONS.PASSES_READ,
  CREATE: AUTH_PERMISSIONS.PASSES_CREATE,
  UPDATE: AUTH_PERMISSIONS.PASSES_UPDATE,
  DELETE: AUTH_PERMISSIONS.PASSES_DELETE,
} as const;

export type PassesPermission =
  (typeof PASSES_PERMISSIONS)[keyof typeof PASSES_PERMISSIONS];
