import { AUTH_PERMISSIONS } from "@/modules/auth/constants/auth.permissions";

export const PROFILE_TYPES_PERMISSIONS = {
  READ: AUTH_PERMISSIONS.PROFILE_TYPES_READ,
  CREATE: AUTH_PERMISSIONS.PROFILE_TYPES_CREATE,
  UPDATE: AUTH_PERMISSIONS.PROFILE_TYPES_UPDATE,
  DELETE: AUTH_PERMISSIONS.PROFILE_TYPES_DELETE,
} as const;

export type ProfileTypesPermission =
  (typeof PROFILE_TYPES_PERMISSIONS)[keyof typeof PROFILE_TYPES_PERMISSIONS];
