import { AUTH_PERMISSIONS } from "@/modules/auth/constants/auth.permissions";

export const ROLLING_MILLS_PERMISSIONS = {
  READ: AUTH_PERMISSIONS.ROLLING_MILLS_READ,
  CREATE: AUTH_PERMISSIONS.ROLLING_MILLS_CREATE,
  UPDATE: AUTH_PERMISSIONS.ROLLING_MILLS_UPDATE,
  DELETE: AUTH_PERMISSIONS.ROLLING_MILLS_DELETE,
} as const;

export type RollingMillsPermission =
  (typeof ROLLING_MILLS_PERMISSIONS)[keyof typeof ROLLING_MILLS_PERMISSIONS];
