import { AUTH_PERMISSIONS } from "@/modules/auth/constants/auth-permissions";

export const CHEMICAL_ELEMENTS_PERMISSIONS = {
  READ: AUTH_PERMISSIONS.CHEMICAL_ELEMENTS_READ,
  CREATE: AUTH_PERMISSIONS.CHEMICAL_ELEMENTS_CREATE,
  UPDATE: AUTH_PERMISSIONS.CHEMICAL_ELEMENTS_UPDATE,
  DELETE: AUTH_PERMISSIONS.CHEMICAL_ELEMENTS_DELETE,
} as const;

export type ChemicalElementsPermission =
  (typeof CHEMICAL_ELEMENTS_PERMISSIONS)[keyof typeof CHEMICAL_ELEMENTS_PERMISSIONS];

export const CHEMICAL_ELEMENTS_PERMISSIONS_VALUES = Object.values(CHEMICAL_ELEMENTS_PERMISSIONS)