export const AUTH_PERMISSIONS = {
  ADMIN: "ADMIN",

  // Calibrations
  CALIBRATIONS_READ: "CALIBRATIONS:READ",
  CALIBRATIONS_CREATE: "CALIBRATIONS:CREATE",
  CALIBRATIONS_UPDATE: "CALIBRATIONS:UPDATE",
  CALIBRATIONS_DELETE: "CALIBRATIONS:DELETE",

  // Passes
  PASSES_READ: "PASSES:READ",
  PASSES_CREATE: "PASSES:CREATE",
  PASSES_UPDATE: "PASSES:UPDATE",
  PASSES_DELETE: "PASSES:DELETE",

  // Users
  USERS_READ: "USERS:READ",
  USERS_CREATE: "USERS:CREATE",
  USERS_UPDATE: "USERS:UPDATE",
  USERS_DELETE: "USERS:DELETE",

  // Roles
  ROLES_READ: "ROLES:READ",
  ROLES_CREATE: "ROLES:CREATE",
  ROLES_UPDATE: "ROLES:UPDATE",
  ROLES_DELETE: "ROLES:DELETE",

  // Rolling Mills
  ROLLING_MILLS_READ: "ROLLING_MILLS:READ",
  ROLLING_MILLS_CREATE: "ROLLING_MILLS:CREATE",
  ROLLING_MILLS_UPDATE: "ROLLING_MILLS:UPDATE",
  ROLLING_MILLS_DELETE: "ROLLING_MILLS:DELETE",

  // Stands
  STANDS_READ: "STANDS:READ",
  STANDS_CREATE: "STANDS:CREATE",
  STANDS_UPDATE: "STANDS:UPDATE",
  STANDS_DELETE: "STANDS:DELETE",

  // Material Grades
  MATERIAL_GRADES_READ: "MATERIAL_GRADES:READ",
  MATERIAL_GRADES_CREATE: "MATERIAL_GRADES:CREATE",
  MATERIAL_GRADES_UPDATE: "MATERIAL_GRADES:UPDATE",
  MATERIAL_GRADES_DELETE: "MATERIAL_GRADES:DELETE",

  // Chemical Elements
  CHEMICAL_ELEMENTS_READ: "CHEMICAL_ELEMENTS:READ",
  CHEMICAL_ELEMENTS_CREATE: "CHEMICAL_ELEMENTS:CREATE",
  CHEMICAL_ELEMENTS_UPDATE: "CHEMICAL_ELEMENTS:UPDATE",
  CHEMICAL_ELEMENTS_DELETE: "CHEMICAL_ELEMENTS:DELETE",

  // Material Compositions
  MATERIAL_COMPOSITIONS_READ: "MATERIAL_COMPOSITIONS:READ",
  MATERIAL_COMPOSITIONS_CREATE: "MATERIAL_COMPOSITIONS:CREATE",
  MATERIAL_COMPOSITIONS_UPDATE: "MATERIAL_COMPOSITIONS:UPDATE",
  MATERIAL_COMPOSITIONS_DELETE: "MATERIAL_COMPOSITIONS:DELETE",

  // Files
  FILES_READ: "FILES:READ",
  FILES_CREATE: "FILES:CREATE",
  FILES_UPDATE: "FILES:UPDATE",
  FILES_DELETE: "FILES:DELETE",

  // Settings — Mill Types
  MILL_TYPES_READ: "MILL_TYPES:READ",
  MILL_TYPES_CREATE: "MILL_TYPES:CREATE",
  MILL_TYPES_UPDATE: "MILL_TYPES:UPDATE",
  MILL_TYPES_DELETE: "MILL_TYPES:DELETE",

  // Settings — Profile Types
  PROFILE_TYPES_READ: "PROFILE_TYPES:READ",
  PROFILE_TYPES_CREATE: "PROFILE_TYPES:CREATE",
  PROFILE_TYPES_UPDATE: "PROFILE_TYPES:UPDATE",
  PROFILE_TYPES_DELETE: "PROFILE_TYPES:DELETE",

  // Settings — Pass Geometry Types
  PASS_GEOMETRY_TYPES_READ: "PASS_GEOMETRY_TYPES:READ",
  PASS_GEOMETRY_TYPES_CREATE: "PASS_GEOMETRY_TYPES:CREATE",
  PASS_GEOMETRY_TYPES_UPDATE: "PASS_GEOMETRY_TYPES:UPDATE",
  PASS_GEOMETRY_TYPES_DELETE: "PASS_GEOMETRY_TYPES:DELETE",
} as const;

export type AuthPermission =
  (typeof AUTH_PERMISSIONS)[keyof typeof AUTH_PERMISSIONS];
