import { AUTH_PERMISSIONS } from "@/modules/auth/constants/auth.permissions";

export const PASS_GEOMETRY_TYPES_PERMISSIONS = {
  READ: AUTH_PERMISSIONS.PASS_GEOMETRY_TYPES_READ,
  CREATE: AUTH_PERMISSIONS.PASS_GEOMETRY_TYPES_CREATE,
  UPDATE: AUTH_PERMISSIONS.PASS_GEOMETRY_TYPES_UPDATE,
  DELETE: AUTH_PERMISSIONS.PASS_GEOMETRY_TYPES_DELETE,
} as const;

export type PassGeometryTypesPermission =
  (typeof PASS_GEOMETRY_TYPES_PERMISSIONS)[keyof typeof PASS_GEOMETRY_TYPES_PERMISSIONS];
